### PR TITLE
update browsers.json

### PR DESCRIPTION
**Pull request by tboyce**

### CODE REVIEW

**Comment by tboyce** [comment]
I pulled down the latest browser list from the BrowserStack REST API, but that appears to be the Selenium browser list. Is there a way to get the JavaScript testing browser list?

**Comment by klamping** [comment]
@tboyce sorry for never getting back to you. I think there was a script I was using to generate the list. looking in to it now.

**Comment by klamping** [comment]
Hmm, not sure what I was using. If you'd like to work off this project, I'm happy to give you write access to it. I don't use the tool anymore.

**Comment by tboyce** [comment]
I could take over the maintenance of this project if you are still interested in doing that.

**Comment by klamping** [comment]
Added you as a collaborator for this repo. I need to also add you as a collab for the NPM module, but need to find my NPM pw first.

**Comment by tboyce** [comment]
any progress on getting access to NPM?

**Comment by klamping** [comment]
Is this you on NPM? https://www.npmjs.com/~tboyce

You should be added as a collaborator in NPM.

**Comment by tboyce** [comment]
Yes, that's me. Thanks.

**Pull request merged**
